stages:
  convert_xml_to_parquet:
    matrix:
      dataname:
        - env_temp
        - star_watt
    cmd: >-
      python -m src.data.convert_from_xml_to_parquet
      data/raw/${item.dataname}.xml
      data/interim/${item.dataname}.parquet
    deps:
      - src/data/convert_from_xml_to_parquet.py
      - data/raw/${item.dataname}.xml
    outs:
      - data/interim/${item.dataname}.parquet

  merge_parquet_files:
    cmd: >-
      python src/data/merge_parquet_files.py
      data/interim/env_temp.parquet
      data/interim/star_watt.parquet
      data/interim/dataset.parquet
    deps:
      - src/data/merge_parquet_files.py
      - data/interim/env_temp.parquet
      - data/interim/star_watt.parquet
    outs:
      - data/interim/dataset.parquet

  build_features:
    cmd: >-
      python src/features/build_features.py
      data/interim/dataset.parquet
      data/interim/features.parquet
    deps:
      - src/features/build_features.py
      - data/interim/dataset.parquet
    outs:
      - data/interim/features.parquet

  split_data:
    cmd: >-
      python src/data/split_data.py
      data/interim/features.parquet
      data/interim/train.parquet
      data/interim/val.parquet
      data/interim/test.parquet
      --train_ratio ${train_model.train_ratio}
      --val_ratio ${train_model.val_ratio}
      --input_length ${train_model.input_length}
    deps:
      - src/data/split_data.py
      - data/interim/features.parquet
    outs:
      - data/interim/train.parquet
      - data/interim/val.parquet
      - data/interim/test.parquet

  train_model:
    cmd: >-
      python -m src.models.train_model
      data/interim/train.parquet
      data/interim/val.parquet
      models/best_model.pth
      --data_fraction ${train_model.data_fraction}
      --n_trials ${train_model.n_trials}
      --num_epochs ${train_model.num_epochs}
      --batch_size ${train_model.batch_size}
      --input_length ${train_model.input_length}
      --output_length ${train_model.output_length}
      --hidden_dim ${train_model.hidden_dim}
    deps:
      - src/models/train_model.py
      - src/models/model.py
      - src/models/dataset.py
      - data/interim/train.parquet
      - data/interim/val.parquet
    outs:
      - models/best_model.pth

  inference:
    matrix:
      dataname:
        - train
        - val
        - test
    cmd: >-
      python -m src.models.inference
      models/best_model.pth
      data/interim/${item.dataname}.parquet
      data/interim/infer_${item.dataname}.parquet
      --batch_size ${train_model.batch_size}
      --device cpu
      --data_fraction ${train_model.data_fraction}
      --input_length ${train_model.input_length}
      --output_length ${train_model.output_length}
    deps:
      - src/models/inference.py
      - src/models/model.py
      - src/models/dataset.py
      - models/best_model.pth
      - data/interim/${item.dataname}.parquet
    outs:
      - data/interim/infer_${item.dataname}.parquet
