stages:
  convert_xml_to_parquet:
    matrix:
      dataname:
        - env_temp
        - star_watt
    cmd: >-
      python -m src.data.convert_from_xml_to_parquet
      data/raw/${item.dataname}.xml
      data/interim/${item.dataname}.parquet
    deps:
      - src/data/convert_from_xml_to_parquet.py
      - data/raw/${item.dataname}.xml
    outs:
      - data/interim/${item.dataname}.parquet
