stages:
  convert_xml_to_parquet:
    matrix:
      dataname:
        - env_temp
        - star_watt
    cmd: >-
      python -m src.data.convert_from_xml_to_parquet
      data/raw/${item.dataname}.xml
      data/interim/${item.dataname}.parquet
    deps:
      - src/data/convert_from_xml_to_parquet.py
      - data/raw/${item.dataname}.xml
    outs:
      - data/interim/${item.dataname}.parquet

  merge_parquet_files:
    cmd: >-
      python src/data/merge_parquet_files.py
      data/interim/env_temp.parquet
      data/interim/star_watt.parquet
      data/interim/dataset.parquet
    deps:
      - src/data/merge_parquet_files.py
      - data/interim/env_temp.parquet
      - data/interim/star_watt.parquet
    outs:
      - data/interim/dataset.parquet

  build_features:
    cmd: >-
      python src/features/build_features.py
      data/interim/dataset.parquet
      data/interim/features.parquet
    deps:
      - src/features/build_features.py
      - data/interim/dataset.parquet
    outs:
      - data/interim/features.parquet

  train_model:
    cmd: >-
      python src/models/train_transformer.py
    deps:
      - src/models/train_transformer.py
      - data/interim/features.parquet
    outs:
      - models/
