train_model:
  data_fraction: 0.01
  n_trials: 2
  num_epochs: 2
  input_sequence_length: 60
  output_sequence_length: 2
  batch_size: 32
  train_ratio: 0.7
  val_ratio: 0.15
  embed_dim: 64
  num_workers: 2
  checkpoint_interval: 1
