train_model:
  data_fraction: 0.1
  n_trials: 1
  num_epochs: 100
  input_sequence_length: 360
  output_sequence_length: 5
  batch_size: 32
  train_ratio: 0.7
  val_ratio: 0.15
  num_workers: 4
  checkpoint_interval: 1
  embed_dim: 20
  nhead: 10
  lr: 0.000514804885292421
